name: Publish package to the Maven Central Repository

on:
  workflow_call:

jobs:
  publish:
    environment: snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish Snapshot to the Maven Central Repository
        run: mvn clean deploy -P nexus-release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.OSSRH_TOKEN }}
