name: Publish && Release

on:
  push:
      branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  snapshot:
    uses: ./.github/workflows/cd-snapshot.yml
    secrets: inherit

