name: Create Pull Request

on:
  workflow_call:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        base: master
        branch: release
        labels: automated pr
        draft: false